import { Memory } from "./types";

export const memory: Memory = {
    categoryList: ["TURNIPS", "CARROTS"],
    notes: {
        "1682188137607ngw9drt": {
            id: "1682188137607ngw9drt",
            note: "This is a fart. A really long fart that will have to go across several lines, hopefully.",
            additionalInfo: "",
            dateAdded: "",
            dateUpdated: "",
            priority: "normal",
            completed: true,
            imageURI: "",
            isNewNote: false,
            lastUpdatedBy: "",
            createdBy: "mockMemory",
            isSecureNote: false,
            locations: [["TURNIPS", ""]],
        },
        "16821881dfsdg37607ngw9drtxxxxxxxx": {
            id: "16821881dfsdg37607ngw9drtxxxxxxxx",
            note: "This is a second note",
            additionalInfo: "",
            dateAdded: "",
            dateUpdated: "",
            priority: "normal",
            completed: false,
            imageURI: "",
            isNewNote: false,
            lastUpdatedBy: "",
            createdBy: "mockMemory",
            isSecureNote: false,
            locations: [["TURNIPS", ""]],
        },
        "1682188rgerghre1dfsdg37607ngw9drtxxxxxxxx": {
            id: "1682188rgerghre1dfsdg37607ngw9drtxxxxxxxx",
            note: "This is a thirdnote",
            additionalInfo: "",
            dateAdded: "",
            dateUpdated: "",
            priority: "normal",
            completed: false,
            imageURI: "",
            isNewNote: false,
            isSecureNote: false,
            lastUpdatedBy: "",
            createdBy: "mockMemory",
            locations: [["CARROTS", ""]],
        },
    },
    categories: {
        TURNIPS: {
            id: "TURNIPS",
            name: "test cat 1",
            subCategories: [],
            notes: [
                { id: "1682188137607ngw9drt", isSecure: false },
                { id: "16821881dfsdg37607ngw9drtxxxxxxxx", isSecure: false },
            ],
            dateAdded: "",
            dateUpdated: "",
            createdBy: "mockMemory",
            lastUpdatedBy: "",
        },
        CARROTS: {
            id: "CARROTS",
            name: "test cat 2",
            subCategories: [""],
            notes: [],
            dateAdded: "",
            dateUpdated: "",
            createdBy: "mockMemory",
            lastUpdatedBy: "",
        },
    },

    subCategories: {
        newsubby11: {
            id: "newsubby11",
            name: "Television",
            notes: [{ id: "1682188rgerghre1dfsdg37607ngw9drtxxxxxxxx", isSecure: false }],
            dateAdded: "",
            dateUpdated: "",
            parentCategory: "randomcatidgggggggggg3",
            createdBy: "mockMemory",
            lastUpdatedBy: "",
            location: ["CARROTS", ""],
        },
    },
};
