import { Memory } from "./types";

export const memory: Memory = {
    categoryList: ["firstcat1", "idofsecondcat"],
    categories: {
        firstcat1: {
            id: "firstcat1",
            name: "First category",
            noteList: [],
            notes: {},
            subCategoryList: ["firstsubcat"],
            subCategories: {
                firstsubcat: {
                    id: "firstsubcat",
                    name: "sub cat name",
                    noteList: ["secondNote"],
                    notes: {
                        secondNote: {
                            id: "secondNote",
                            note: "This is the second note",
                            additionalInfo: "",
                            dateAdded: "8/11/88",
                            dateUpdated: "",
                            priority: "",
                            completed: false,
                            imageURI: "",
                            isNewNote: false,
                            createdBy: "mockMemory",
                            lastUpdatedBy: "",
                            isSecureNote: false,
                            parents: ["firstcat1", "firstsubcat"],
                            otherLocations: [],
                        },
                    },
                    dateAdded: "8/11/88",
                    dateUpdated: "",
                    createdBy: "mockMemory",
                    lastUpdatedBy: "",
                    parents: ["firstcat1", ""],
                },
            },
            dateAdded: "8/11/88",
            dateUpdated: "",
            createdBy: "mock memory",
            lastUpdatedBy: "",
        },
        idofsecondcat: {
            id: "idofsecondcat",
            name: "Second category",
            noteList: ["firstNote", "anothernote"],
            notes: {
                firstNote: {
                    id: "firstNote",
                    note: "This is the first note",
                    additionalInfo: "",
                    dateAdded: "8/11/88",
                    dateUpdated: "",
                    priority: "",
                    completed: false,
                    imageURI: "",
                    isNewNote: false,
                    createdBy: "mockMemory",
                    lastUpdatedBy: "",
                    isSecureNote: false,
                    parents: ["idofsecondcat", ""],
                    otherLocations: [],
                },
                anothernote: {
                    id: "anothernote",
                    note: "New note. Expect notes and cats in this cat to update but not in the other.",
                    additionalInfo: "",
                    dateAdded: "8/11/88",
                    dateUpdated: "",
                    priority: "",
                    completed: false,
                    imageURI: "",
                    isNewNote: false,
                    createdBy: "mockMemory",
                    lastUpdatedBy: "",
                    isSecureNote: false,
                    parents: ["idofsecondcat", ""],
                    otherLocations: [],
                },
            },
            subCategoryList: [],
            subCategories: {},
            dateAdded: "8/11/88",
            dateUpdated: "",
            createdBy: "mock memory",
            lastUpdatedBy: "",
        },
    },
};
