import { Memory } from "./types";

export const memory: Memory = {
    categoryList: [
        "randomcatid1",
        "randomcatid2",
        "randomcatid3",
        "randomcatidgsgagergre3",
        "randogefewfmcatid3",
        "randomcwefwdatid3",
        "randtwertgwfomcatid3",
        "randomcfsegsaxcsafgerhratid3",
        "randefewgryhrtjhomcatid3",
        "randomcatidgggggggggg3",
    ],
    notes: {
        "1682188137607ngw9drt": {
            id: "1682188137607ngw9drt",
            note: "This is a fart. A really long fart that will have to go across several lines, hopefully.",
            additionalInfo: "",
            dateAdded: "",
            dateUpdated: "",
            priority: "normal",
            completed: true,
            imageURI: "",
            isNewNote: false,
        },
        "16821881dfsdg37607ngw9drtxxxxxxxx": {
            id: "16821881dfsdg37607ngw9drtxxxxxxxx",
            note: "This is a second note",
            additionalInfo: "",
            dateAdded: "",
            dateUpdated: "",
            priority: "normal",
            completed: false,
            imageURI: "",
            isNewNote: false,
        },
        "1682188rgerghre1dfsdg37607ngw9drtxxxxxxxx": {
            id: "1682188rgerghre1dfsdg37607ngw9drtxxxxxxxx",
            note: "This is a thirdnote",
            additionalInfo: "",
            dateAdded: "",
            dateUpdated: "",
            priority: "normal",
            completed: false,
            imageURI: "",
            isNewNote: false,
        },
    },
    categories: {
        randomcatid1: {
            id: "randomcatid1",
            name: "test cat 1",
            subCategories: ["newsubby11", "othernewsubby22", "randomsubcatid1"],
            notes: [],
            dateAdded: "",
            dateUpdated: "",
        },
        randomcatid2: {
            id: "randomcatid2",
            name: "test cat 2",
            subCategories: ["randomsubcatid2"],
            notes: [],
            dateAdded: "",
            dateUpdated: "",
        },
        randomcatid3: {
            id: "randomcatid3",
            name: "test cat 3 - no subs",
            subCategories: ["randomsubcatid21", "randomsubcatid22"],
            notes: [],
            dateAdded: "",
            dateUpdated: "",
        },
        randomcatidgsgagergre3: {
            id: "randomcatidgsgagergre3",
            name: "test cat 3 - no sugregefegfbs",
            notes: [
                "1682188137607ngw9drt",
                "16821881dfsdg37607ngw9drtxxxxxxxx",
                "1682188rgerghre1dfsdg37607ngw9drtxxxxxxxx",
            ],
            subCategories: [],
            dateAdded: "",
            dateUpdated: "",
        },
        randogefewfmcatid3: {
            id: "randogefewfmcatid3",
            name: "test wefgewfgwecat 3 - no subs",
            notes: [
                "1682188137607ngw9drt",
                "16821881dfsdg37607ngw9drtxxxxxxxx",
                "1682188rgerghre1dfsdg37607ngw9drtxxxxxxxx",
            ],
            subCategories: [],
            dateAdded: "",
            dateUpdated: "",
        },
        randomcwefwdatid3: {
            id: "randomcwefwdatid3",
            name: "testedfweftjrt cat 3 - no subs",
            notes: [
                "1682188137607ngw9drt",
                "16821881dfsdg37607ngw9drtxxxxxxxx",
                "1682188rgerghre1dfsdg37607ngw9drtxxxxxxxx",
            ],
            subCategories: [],
            dateAdded: "",
            dateUpdated: "",
        },
        randtwertgwfomcatid3: {
            id: "randtwertgwfomcatid3",
            name: "test cat 3 - no fewfwegergsubs",
            notes: [
                "1682188137607ngw9drt",
                "16821881dfsdg37607ngw9drtxxxxxxxx",
                "1682188rgerghre1dfsdg37607ngw9drtxxxxxxxx",
            ],
            subCategories: [],
            dateAdded: "",
            dateUpdated: "",
        },
        randomcfsegsaxcsafgerhratid3: {
            id: "randomcfsegsaxcsafgerhratid3",
            name: "test cadrsfg j fedfwef wefewdf kk kk kk kk kk kk",
            notes: [
                "1682188137607ngw9drt",
                "16821881dfsdg37607ngw9drtxxxxxxxx",
                "1682188rgerghre1dfsdg37607ngw9drtxxxxxxxx",
            ],
            subCategories: [],
            dateAdded: "",
            dateUpdated: "",
        },
        randefewgryhrtjhomcatid3: {
            id: "randefewgryhrtjhomcatid3",
            name: "test cat 3 - no gsdfgsdfgsdsubs",
            notes: [
                "1682188137607ngw9drt",
                "16821881dfsdg37607ngw9drtxxxxxxxx",
                "1682188rgerghre1dfsdg37607ngw9drtxxxxxxxx",
            ],
            subCategories: [],
            dateAdded: "",
            dateUpdated: "",
        },
        randomcatidgggggggggg3: {
            id: "randomcatidgggggggggg3",
            name: "test cat 3 - no subeeeeeees",
            notes: [
                "1682188137607ngw9drt",
                "16821881dfsdg37607ngw9drtxxxxxxxx",
                "1682188rgerghre1dfsdg37607ngw9drtxxxxxxxx",
            ],
            subCategories: [],
            dateAdded: "",
            dateUpdated: "",
        },
    },

    subCategories: {
        newsubby11: {
            id: "newsubby11",
            name: "Television",
            notes: [
                "1682188137607ngw9drt",
                "16821881dfsdg37607ngw9drtxxxxxxxx",
                "1682188rgerghre1dfsdg37607ngw9drtxxxxxxxx",
            ],
            dateAdded: "",
            dateUpdated: "",
            parentCategory: "randomcatidgggggggggg3",
        },
        othernewsubby22: {
            id: "othernewsubby22",
            name: "Books",
            notes: [
                "1682188137607ngw9drt",
                "16821881dfsdg37607ngw9drtxxxxxxxx",
                "1682188rgerghre1dfsdg37607ngw9drtxxxxxxxx",
            ],
            dateAdded: "",
            dateUpdated: "",
            parentCategory: "randomcatidgggggggggg3",
        },
        randomsubcatid1: {
            id: "randomsubcatid1",
            name: "sub cat 1",
            notes: [
                "1682188137607ngw9drt",
                "16821881dfsdg37607ngw9drtxxxxxxxx",
                "1682188rgerghre1dfsdg37607ngw9drtxxxxxxxx",
            ],
            dateAdded: "",
            dateUpdated: "",
            parentCategory: "randomcatid1",
        },
        randomsubcatid2: {
            id: "randomsubcatid2",
            name: "sub cat 2",
            notes: [
                "1682188137607ngw9drt",
                "16821881dfsdg37607ngw9drtxxxxxxxx",
                "1682188rgerghre1dfsdg37607ngw9drtxxxxxxxx",
            ],
            dateAdded: "",
            dateUpdated: "",
            parentCategory: "randomcatid1",
        },
        randomsubcatid21: {
            id: "randomsubcatid21",
            name: "sub cat 21",
            notes: [
                "1682188137607ngw9drt",
                "16821881dfsdg37607ngw9drtxxxxxxxx",
                "1682188rgerghre1dfsdg37607ngw9drtxxxxxxxx",
            ],
            dateAdded: "",
            dateUpdated: "",
            parentCategory: "randomcatid2",
        },
        randomsubcatid22: {
            id: "randomsubcatid22",
            name: "sub cat 22",
            notes: [
                "1682188137607ngw9drt",
                "16821881dfsdg37607ngw9drtxxxxxxxx",
                "1682188rgerghre1dfsdg37607ngw9drtxxxxxxxx",
            ],
            dateAdded: "",
            dateUpdated: "",
            parentCategory: "randomcatid2",
        },
    },
};
